version: '3.5' 
services: 
    frontend:
      build: ./fe
      depends_on:
        - backend
      ports:
          - 5000:5000
    backend:
      build: ./be
      environtment:
        - REDIS_HOST: redis
      depends_on:
        - redis
      ports:
          - 8080:8080
    redis:
      image: redis
      container_name: cache
      restart: unless-stopped