FROM ubuntu:latest

EXPOSE 8080

WORKDIR /usr/src/app

COPY . .

RUN apt-get update && apt-get install -y curl
RUN rm -rf /usr/local/go 
RUN curl https://golang.org/dl/go1.16.3.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.17.1.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin

ENV REQUEST_ORIGIN http://localhost:5000

RUN go version

RUN go build

RUN go test ./...

CMD ./server